#!/bin/bash

echo "🚀 Configuration des variables d'environnement sur Vercel"
echo ""
echo "📋 Variables à ajouter sur Vercel :"
echo "=================================="
echo ""
echo "1. RESEND_API_KEY"
echo "   Valeur: re_Mksui53X_CFrkxKtg8YuViZhHmeZNSbmR"
echo ""
echo "2. NEXT_PUBLIC_APP_URL"
echo "   Valeur: https://laia-skin-institut-as92.vercel.app"
echo ""
echo "3. DATABASE_URL"
echo "   Valeur: postgresql://postgres.zsxweurvtsrdgehtadwa:%23SBxrx8kVc857Ed@aws-1-eu-west-3.pooler.supabase.com:6543/postgres?pgbouncer=true"
echo ""
echo "=================================="
echo ""
echo "👉 Pour configurer :"
echo "1. Allez sur: https://vercel.com/celia92000s-projects/laia-skin-institut-as92/settings/environment-variables"
echo "2. Ajoutez chaque variable ci-dessus"
echo "3. Cliquez sur 'Save' pour chaque variable"
echo "4. Redéployez l'application (onglet Deployments > ... > Redeploy)"
echo ""
echo "✅ Une fois configuré, les emails seront envoyés automatiquement !"